AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rerank

  Sample SAM Template for rerank

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  RerankFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 10240
      PackageType: Image
      Events:
        Rerank:
          Type: Api
          Properties:
            Path: /rerank
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest
